### ISSUE TITLE
Link to Main.hs in README.MD doesn't work

### ISSUE THREAD

**Issue by habbler** [louispan/pipes-fluid#1]
It points to https://github.com/louispan/pipes-fluid/blob/master/app/Main.hs which does not seem to exist

**Comment by louispan** [comment]
Thanks for bringing this up. I've updated [README.md](https://github.com/louispan/pipes-fluid/blob/master/README.md) to link to [Spec.hs](https://github.com/louispan/pipes-fluid/blob/master/test/Spec.hs). And updated the link to glazier-tutorial.
