### ISSUE TITLE
Slides are no longer available

### ISSUE THREAD

**Issue by qrilka** [louispan/pipes-fluid#2]
Slideshare says:
```
Uploaded Content Removed
```

**Comment by louispan** [comment]
I'll put it back in two days. I'll have to remove old info from the slodes

**Comment by louispan** [comment]
Sorry about closing the issue - don't know what happened on my iphone browser

**Comment by louispan** [comment]
I've moved the info from the slides to a wiki [Signals wiki](https://github.com/louispan/pipes-fluid/wiki/Signals).

**Comment by louispan** [comment]
Now, I can close the issue properly. NB. I removed the glazier-tutorial link as it is out of date - and I will not be updating it. I've been experimenting with completely different [glazier-react-widgets](https://github.com/louispan/glazier-react-widget/tree/data-diverse) framework which doesn't use Signals.
